// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0WpZNn2xsAF6XkhOkBr2JDpjOg5mtkY',
    appId: '1:696597372697:web:d79c96e585ff73f282af88',
    messagingSenderId: '696597372697',
    projectId: 'btl-music-app-flutter',
    authDomain: 'btl-music-app-flutter.firebaseapp.com',
    storageBucket: 'btl-music-app-flutter.firebasestorage.app',
    measurementId: 'G-ZXJQXLQ8EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCtHS4jJedwUhD8QZVOEQU-pA3swtg1fs',
    appId: '1:696597372697:android:69a31c724848284182af88',
    messagingSenderId: '696597372697',
    projectId: 'btl-music-app-flutter',
    storageBucket: 'btl-music-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXPQiKr_7-pKMVLnQltdS6OmhEsSICjCo',
    appId: '1:696597372697:ios:62003033e858813e82af88',
    messagingSenderId: '696597372697',
    projectId: 'btl-music-app-flutter',
    storageBucket: 'btl-music-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.btlMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXPQiKr_7-pKMVLnQltdS6OmhEsSICjCo',
    appId: '1:696597372697:ios:62003033e858813e82af88',
    messagingSenderId: '696597372697',
    projectId: 'btl-music-app-flutter',
    storageBucket: 'btl-music-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.btlMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0WpZNn2xsAF6XkhOkBr2JDpjOg5mtkY',
    appId: '1:696597372697:web:3a6e6ef51f75df5682af88',
    messagingSenderId: '696597372697',
    projectId: 'btl-music-app-flutter',
    authDomain: 'btl-music-app-flutter.firebaseapp.com',
    storageBucket: 'btl-music-app-flutter.firebasestorage.app',
    measurementId: 'G-75M0T13VVE',
  );

}